export const EV_MODELS = [
  { brand: "VinFast", model: "VF 3", plugType: "CCS2", batteryKwh: 18.64 },
  { brand: "VinFast", model: "VF 5", plugType: "CCS2", batteryKwh: 37.23 },
  { brand: "VinFast", model: "VF e34", plugType: "CCS2", batteryKwh: 44.5 },
  { brand: "VinFast", model: "VF 6", plugType: "CCS2", batteryKwh: 59.6 },
  { brand: "VinFast", model: "VF 7", plugType: "CCS2", batteryKwh: 75.3 },
  { brand: "VinFast", model: "VF 8", plugType: "CCS2", batteryKwh: 82 },
  { brand: "VinFast", model: "VF 9", plugType: "CCS2", batteryKwh: 92 },
  { brand: "BYD", model: "Atto 3", plugType: "CCS2", batteryKwh: 49.9 },
  { brand: "BYD", model: "Dolphin", plugType: "CCS2", batteryKwh: 44.9 },
  { brand: "BYD", model: "Seal", plugType: "CCS2", batteryKwh: 61.4 },
  { brand: "Tesla", model: "Model 3 RWD", plugType: "CCS2", batteryKwh: 57.5 },
  { brand: "Tesla", model: "Model 3 Long Range", plugType: "CCS2", batteryKwh: 82 },
  { brand: "Tesla", model: "Model Y RWD", plugType: "CCS2", batteryKwh: 60 },
  { brand: "Tesla", model: "Model Y Long Range", plugType: "CCS2", batteryKwh: 75 },
  { brand: "Hyundai", model: "IONIQ 5 Standard", plugType: "CCS2", batteryKwh: 58 },
  { brand: "Hyundai", model: "IONIQ 5 Long Range", plugType: "CCS2", batteryKwh: 72.6 },
  { brand: "Hyundai", model: "Kona EV", plugType: "CCS2", batteryKwh: 64 },
  { brand: "Kia", model: "EV6 Standard", plugType: "CCS2", batteryKwh: 58 },
  { brand: "Kia", model: "EV6 Long Range", plugType: "CCS2", batteryKwh: 77.4 },
  { brand: "Kia", model: "Niro EV", plugType: "CCS2", batteryKwh: 64.8 },
  { brand: "MG", model: "MG4 Standard", plugType: "CCS2", batteryKwh: 51 },
  { brand: "MG", model: "ZS EV Long Range", plugType: "CCS2", batteryKwh: 51.1 },
  { brand: "Mercedes-Benz", model: "EQA 250", plugType: "CCS2", batteryKwh: 66.5 },
  { brand: "Mercedes-Benz", model: "EQB 300", plugType: "CCS2", batteryKwh: 66.5 },
  { brand: "Mercedes-Benz", model: "EQS 450+", plugType: "CCS2", batteryKwh: 108.4 },
  { brand: "Porsche", model: "Taycan RWD", plugType: "CCS2", batteryKwh: 79.2 },
  { brand: "Porsche", model: "Taycan 4S", plugType: "CCS2", batteryKwh: 93.4 },
  { brand: "Audi", model: "e-tron 55", plugType: "CCS2", batteryKwh: 95 },
  { brand: "Audi", model: "e-tron GT", plugType: "CCS2", batteryKwh: 93.4 },
];